### ISSUE TITLE
add test for IP using direct dns query

### ISSUE THREAD

**Issue by TonyLHansen** [ScottHelme/CloudFlareDDNS#4]
It is more efficient if you do a direct DNS query before doing the more expensive HTTP call from CloudFlare: 

Add this before the code starting at:

// Build the initial request to fetch the record ID.

$dnsa = gethostbyname($ddnsAddress);
if ($ip != $dnsa) {

and a } at the end.

**Comment by ScottHelme** [comment]
True, but the difference here is fairly minimal. If you'd like to fork and submit a pull request with changes I can take a look, but for now I think it's ok. Thanks!
