### ISSUE TITLE
need to capture service_mode value

### ISSUE THREAD

**Issue by TonyLHansen** [ScottHelme/CloudFlareDDNS#5]
The value passed to the update has a value for service_mode. This value needs to be captured from the rec_load_all API call.

Add this variable after $cfIP:

$serviceMode  = '';                                             // The service_mode for the subdomain

Set it after setting $cfIP:

$serviceMode = $rec->service_mode;

Use it in the rec_edit API call:

                        'service_mode' => urlencode($serviceMode),

**Comment by ScottHelme** [comment]
The service_mode is now set to 0 so that traffic is not directed through CloudFlare. The value can be changed based on your needs.
