### ISSUE TITLE
Updating multiple hosts of multiple root domains

### ISSUE THREAD

**Issue by mikerun** [ScottHelme/CloudFlareDDNS#8]
what about updating multiple hosts of multiple root domains I'm thinking of modifying the script to my specific configuration but I'm sure you have a better approach than me that would be more generic?

**Comment by ScottHelme** [comment]
The script could be easily modified to update multiple domains if you wish. For now, I'd like to keep it as a simple DDNS script for personal use. Please feel free to fork and submit a pull request if you put something together.
